POST http://localhost:3000/api/todos.json HTTP/1.1
Content-Type: application/json

{
   "subject": "general",
   "task": "do something",
   "dateAdded": "2022-01-21",
   "dateDue": "2022-01-30",
   "status": "pending"
}